### ISSUE TITLE
Bitbucket integration

### ISSUE THREAD

**Issue by eschizoid** [atomist/automation-client-ts#103] opened 2017-11-17 16:44 UTC
It would be ideal if there was support for private version control systems such as Bitbucket

**Comment by johnsonr** [comment] 2017-11-18 04:30
Thanks for the issue raising. I've closed as a duplicate of #51. Would love to hear more there about what you're thinking--I'm assuming support for clone in `GitCommandGitProject`.

**Closed by johnsonr** 2017-11-18 04:30 UTC
Labels: duplicate
